import Head from 'next/head';
import React, { Fragment, useState } from 'react';

import Footer from './Footer';
import Header from './Header';
import Sidebar from './Sidebar';

interface iProps {
  children: React.ReactElement;
  title: string;
}

const Layout = ({ children, title = 'Health Dashboard' }: iProps) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex w-[screen]'>
        <div className='md:w-[14%]'>
          <Sidebar />
        </div>
        <div className='flex-grow mx-auto h-[100%]'>
          <Header />
          {children}
          <Footer />
        </div>
      </div>
    </>
  );
};

export default Layout;
